// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNw_R5DQM_fnD5vQZ3d2ZKLh9TjyP3pjA',
    appId: '1:43931391004:web:7ba07345c9fce65878fbd9',
    messagingSenderId: '43931391004',
    projectId: 'workoutamw',
    authDomain: 'workoutamw.firebaseapp.com',
    storageBucket: 'workoutamw.appspot.com',
    measurementId: 'G-Z987FL7ZYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xXTSxwA4a5DafoBfwqNpbZXGpMSv4Lw',
    appId: '1:43931391004:android:4de731d0e6b9bcb278fbd9',
    messagingSenderId: '43931391004',
    projectId: 'workoutamw',
    storageBucket: 'workoutamw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpnjzVs9Hf6CTbHWhVa2sXnCTa12OaNE',
    appId: '1:43931391004:ios:a2cee88b3aae9c0478fbd9',
    messagingSenderId: '43931391004',
    projectId: 'workoutamw',
    storageBucket: 'workoutamw.appspot.com',
    iosBundleId: 'com.example.workoutamw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzpnjzVs9Hf6CTbHWhVa2sXnCTa12OaNE',
    appId: '1:43931391004:ios:a2cee88b3aae9c0478fbd9',
    messagingSenderId: '43931391004',
    projectId: 'workoutamw',
    storageBucket: 'workoutamw.appspot.com',
    iosBundleId: 'com.example.workoutamw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNw_R5DQM_fnD5vQZ3d2ZKLh9TjyP3pjA',
    appId: '1:43931391004:web:d545482c050269bb78fbd9',
    messagingSenderId: '43931391004',
    projectId: 'workoutamw',
    authDomain: 'workoutamw.firebaseapp.com',
    storageBucket: 'workoutamw.appspot.com',
    measurementId: 'G-T5SWFPZ3L0',
  );
}
